# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
