# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
