# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40)),
                ('g_img', models.CharField(max_length=100)),
                ('g_price', models.FloatField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
