# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 04:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carts'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carts',
            managers=[
                ('mine_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
