# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 16:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190317_2116'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderdetail',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
