# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190318_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
